site_name: Engenharia de Dados SATC
site_description: Documentação do projeto Pipeline de Dados com PySpark, Delta Lake e Azure
site_author: Prof. Nome do Responsável ou Grupo SATC
site_url: 
site_favicon: images/favicon.png
site_logo: images/logo.png
site_keywords: Engenharia de Dados, Engenharia de Software, SATC, Python, Pyspark, Delta, Jupyter, Git, GitHub, Markdown, MkDocs, Material Theme

repo_name: projeto-ed-satc
repo_url: 
edit_uri: edit/main/docs/

docs_dir: docs

nav:
  - Home: index.md
  - Sobre: sobre.md
  - Arquitetura da Solução: arquitetura.md
  - Camadas: camadas.md
  - Exemplos de Código: exemplos.md

theme:
  name: material
  palette:
    primary: blue
    accent: light-blue
  language: pt
  features:
    - navigation.footer
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.path
    - navigation.top
    - navigation.next-prev
    - search
  icon:
    repo: fontawesome/brands/github

hide:
  - search
  - navigation
  - toc

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/seu-usuario
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/seu-perfil
  generator: false

copyright: >
  © 2025 Projeto de Engenharia de Dados - SATC. Todos os direitos reservados.

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/extra.js

plugins:
  - search
  - mkdocstrings:
      default_handler: python

markdown_extensions: 
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
